package com.stevpet.sonar.plugins.dotnet.mscover.vstowrapper;

import java.io.File;

public interface VisualStudioProject {

    /**
     * get the name of the assembly generated by this project
     * @return
     */
    String getAssemblyName();

    File getArtifact(String buildConfiguration, String buildPlatform);

    boolean isUnitTest();

    String getArtifactName();

    File getDirectory();

    String getName();

    boolean isTest();

}