/*******************************************************************************
 *
 * SonarQube MsCover Plugin
 * Copyright (C) 2015 SonarSource
 * dev@sonar.codehaus.org
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02
 *
 * Author: Peter Stevens, peter@famstevens.eu
 *******************************************************************************/
package com.stevpet.sonar.plugins.dotnet.mscover.vstest.runner;

import com.stevpet.sonar.plugins.dotnet.mscover.vstest.command.VSTestCommand;

public interface VsTestRunner {

   void setSonarPath(String path);

    void setDoCodeCoverage(boolean doCodeCoverage);

    boolean shouldRun();

    /**
     * if mode is set to runvstest the runner will attempt to run test & obtain coverage
     * information. Make sure all properties are set:
     * -solutionDirectory
     * -outputPath
     * Result is the .cover file
     * @return
     */
    void runTests();

    VSTestCommand prepareTestCommand();

    /**
     * parse test log to get paths to result files
     */
   void getResultPaths();


    /**
     * sets the path to the .cover file
     * @param coveragePath
     */
    void setCoveragePath(String coveragePath);

    String getResultsXmlPath();

    void setResultsPath(String resultsPath);

    String getCoverageXmlPath();


    /**
     * Remove the files generated by VsTest. Requires that the sonarPath is set, and that it ends with .sonar
     */
    void clean();

}