package com.stevpet.sonar.plugins.dotnet.mscover.vstest.runner;

import java.io.File;

import com.stevpet.sonar.plugins.dotnet.mscover.vstowrapper.VisualStudioSolution;
import com.stevpet.sonar.plugins.dotnet.mscover.MsCoverProperties;
import com.stevpet.sonar.plugins.dotnet.mscover.vstest.command.VSTestCommand;

public interface VsTestRunner {

   void setSonarPath(String path);

    String getSonarPath();

    void setPropertiesHelper(MsCoverProperties propertiesHelper);

    void setSolution(VisualStudioSolution solution);

    void setSolutionDirectory(File solutionDirectory);

    File getSolutionDirectory();

    void setDoCodeCoverage(boolean doCodeCoverage);

    boolean shouldRun();

    /**
     * if mode is set to runvstest the runner will attempt to run test & obtain coverage
     * information. Make sure all properties are set:
     * -solutionDirectory
     * -outputPath
     * Result is the .cover file
     * @return
     */
    void runTests();

    VSTestCommand prepareTestCommand();

    /**
     * parse test log to get paths to result files
     */
   void getResultPaths();

    /**
     * gets the path to the .cover file
     * @return
     */
    String getCoveragePath();

    /**
     * sets the path to the .cover file
     * @param coveragePath
     */
    void setCoveragePath(String coveragePath);

    String getResultsXmlPath();

    void setResultsPath(String resultsPath);

    String getCoverageXmlPath();

    void setCoverageXmlPath(String outputPath);

    /**
     * Remove the files generated by VsTest. Requires that the sonarPath is set, and that it ends with .sonar
     */
    void clean();

}